# Generated by Django 5.2.5 on 2025-08-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_history_category_alter_history_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory'),
        ),
    ]
